export default [
    {
        title:'首页',
        key:'/admin/home',
        icon:'form',
        children:[{
                title:'首页3',
                key:'/admin/home1'
            },
            {
                title:'首页2',
                key:'/admin/home3'
            }
        ]
    },
    {
        title:'首页4',
        key:'/admin/home4',
        icon:'check-circle',
        children:[{
            title:'首页5',
            key:'/admin/home5'
        },
            {
                title:'首页6',
                key:'/admin/home6'
            }
        ]
    }
 ]
